name: Build and Package ROS 2 Installer

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify correct Ubuntu version

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python and install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        # Install necessary system dependencies
        sudo apt install -y debhelper \
          curl \
          software-properties-common \
          locales \
          build-essential \
          fakeroot \
          devscripts \
          dh-make \
          libtool \
          dh-python
        # Install ROS 2 dependencies via pip
        python3 -m pip install colcon-common-extensions

    # Build the .deb package without using debian/rules
    - name: Build the .deb package
      run: dpkg-buildpackage -us -uc -b -d

    # Upload the built .deb package as an artifact
    - name: Upload .deb package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ros2-installer-deb
        path: ../*.deb
