name: Build and Package ROS 2 Installer

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-22.04  # You can adjust this to use a different Ubuntu version if necessary

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install ROS 2 dependencies and add repositories
    - name: Add ROS 2 repository and install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros2.repos -o /tmp/ros2.repos
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions \
          debhelper \
          curl \
          software-properties-common \
          locales \
          build-essential \
          fakeroot \
          devscripts \
          dh-make \
          libtool \
          dh-python

    # Make debian/rules executable
    - name: Make debian/rules executable
      run: chmod +x debian/rules

    # Build the .deb package
    - name: Build the .deb package
      run: dpkg-buildpackage -us -uc -b -d

    # Upload the built .deb package as an artifact (optional)
    - name: Upload .deb package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ros2-installer-deb
        path: ../*.deb
